"""make email unique

Revision ID: 2f19e2b6ca21
Revises: 7ca00a7171c4
Create Date: 2025-12-04 16:28:58.484823

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f19e2b6ca21"
down_revision: Union[str, Sequence[str], None] = "7ca00a7171c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала удаляем дубликаты email (оставляем только запись с минимальным id)
    op.execute("""
        DELETE FROM users
        WHERE id NOT IN (
            SELECT MIN(id)
            FROM users
            GROUP BY email
        )
    """)
    # Теперь создаём уникальный индекс
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    # ### end Alembic commands ###
