"""added a new parameter - created_at

Revision ID: 589c9ed945b6
Revises: 8343badeabdc
Create Date: 2025-12-19 15:22:11.730293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "589c9ed945b6"
down_revision: Union[str, Sequence[str], None] = "8343badeabdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "created_at")
    # ### end Alembic commands ###
