"""add users some columns added

Revision ID: 7ca00a7171c4
Revises: 0d96c58a68c1
Create Date: 2025-12-02 15:40:26.877348

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ca00a7171c4"
down_revision: Union[str, Sequence[str], None] = "0d96c58a68c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(length=100), nullable=False))
    op.add_column("users", sa.Column("surname", sa.String(length=100), nullable=False))
    op.add_column("users", sa.Column("username", sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "username")
    op.drop_column("users", "surname")
    op.drop_column("users", "name")
    # ### end Alembic commands ###
